---
# handlers file for ansible-postfix
- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: reload postfix
  service:
    name: postfix
    state: reloaded

- name: start postfix
  service:
    name: postfix
    state: started

- name: stop postfix
  service:
    name: postfix
    state: stopped

- name: reload systemd
  command: systemctl daemon-reload

- name: update postmap files permissions
  file:
    path: "/etc/postfix/{{ item }}.db"
    mode: '0600'
  with_items: "{{ postfix_postmap_files | default([]) }}"
  tags:
    - postfix
    - config
